image: 10.0.0.101:5000/ubuntu-loaded

stages:
  - build
  - version
  - release
  - test


build:
  stage: build
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh build.sh
  artifacts:
    paths:
      - lib/**
      - bin/Release/**


version:
  stage: version
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh 'sh increment-version.sh'
    - sh 'sh push-version.sh'
  artifacts:
    paths:
      - buildnumber.txt
      - version.txt
      - full-version.txt

release:
  stage: release
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh 'bash create-release-zip.sh'
    - sh 'bash publish-github-release.sh'
  dependencies:
    - build
    - version

test:
  stage: test
  tags:
    - docker
  script:
    - git checkout "$CI_COMMIT_BRANCH"
    - sh test-download-and-install.sh
