image: 10.0.0.101:5000/ubuntu-loaded

stages:
  - build
  - version
  - release
  - test


build:
  stage: build
  tags:
    - docker
  script:
    - git config --global user.email "admin@makerzone.com.au"
    - git config --global user.name "John Rebbeck"
    - git checkout "$CI_COMMIT_BRANCH"
    - git pull
    - sh build.sh
  artifacts:
    paths:
      - lib/**
      - bin/Release/**


version:
  stage: version
  tags:
    - docker
  script:
    - git config --global user.email "admin@makerzone.com.au"
    - git config --global user.name "John Rebbeck"
    - git checkout "$CI_COMMIT_BRANCH"
    - git pull
    - git remote set-url origin https://$GHTOKEN@github.com/GrowSense/Installer.git
    - git remote add lan https://10.0.0.101:180/growsense/installer.git || echo "Skipping"
    - sh increment-version.sh
    - sh push-version.sh
  artifacts:
    paths:
      - buildnumber.txt
      - version.txt
      - full-version.txt

release:
  stage: release
  tags:
    - docker
  script:
    - bash create-release-zip.sh
    - bash publish-github-release.sh
  dependencies:
    - build
    - version

test:
  stage: test
  tags:
    - docker
  script:
    - sh test-download-and-install.sh
