image: 10.0.0.101:5000/ubuntu-loaded

stages:
  - build
  - version
  - release
  - test
  - graduate

build:
  stage: build
  tags:
    - docker
  before_script:
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH"
    - git pull -f
    - cat full-version.txt
  script:
    - sh init.sh
    - sh build.sh
  artifacts:
    paths:
      - lib/**
      - bin/Release/**

release:
  stage: release
  tags:
    - docker	
  before_script:
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH"
    - git pull -f
    - cat full-version.txt
  script:
    - bash create-release-zip.sh
    - bash publish-github-release.sh
  dependencies:
    - build

test:
  stage: test
  tags:
    - docker
  before_script:
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH"
    - git pull -f
    - cat full-version.txt
  script:
    - sh test.sh
  dependencies:
    - build
    
graduate:
  stage: graduate
  tags:
    - docker
  before_script:
    - git remote set-url origin https://$GHTOKEN@github.com/GrowSense/Installer.git
    - git remote add lan http://Internal:$GLTOKEN@10.0.0.101:180/growsense/installer.git || git remote set-url lan http://Internal:$GLTOKEN@10.0.0.101:180/growsense/installer.git
    - git remote add local http://Internal:$GITLAB_TOKEN_LOCAL@$GITLAB_HOST:180/growsense/installer.git || git remote set-url local http://Internal:$GITLAB_TOKEN_LOCAL@$GITLAB_HOST:180/growsense/installer.git
    - git config --global user.email "compulsivecoder@gmail.com"
    - git config --global user.name "CompulsiveCoder"
    - git checkout "$CI_COMMIT_BRANCH"
    - cat full-version.txt
    - git pull -f
  script:
    - sh graduate.sh
